/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddTask {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TaskFilter {
    }
    interface TaskList {
        "tasks": string[];
    }
}
export interface AddTaskCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAddTaskElement;
}
export interface TaskListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTaskListElement;
}
declare global {
    interface HTMLAddTaskElement extends Components.AddTask, HTMLStencilElement {
    }
    var HTMLAddTaskElement: {
        prototype: HTMLAddTaskElement;
        new (): HTMLAddTaskElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTaskFilterElement extends Components.TaskFilter, HTMLStencilElement {
    }
    var HTMLTaskFilterElement: {
        prototype: HTMLTaskFilterElement;
        new (): HTMLTaskFilterElement;
    };
    interface HTMLTaskListElement extends Components.TaskList, HTMLStencilElement {
    }
    var HTMLTaskListElement: {
        prototype: HTMLTaskListElement;
        new (): HTMLTaskListElement;
    };
    interface HTMLElementTagNameMap {
        "add-task": HTMLAddTaskElement;
        "my-component": HTMLMyComponentElement;
        "task-filter": HTMLTaskFilterElement;
        "task-list": HTMLTaskListElement;
    }
}
declare namespace LocalJSX {
    interface AddTask {
        "onTaskAdded"?: (event: AddTaskCustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TaskFilter {
    }
    interface TaskList {
        "onTaskCompleted"?: (event: TaskListCustomEvent<string>) => void;
        "tasks"?: string[];
    }
    interface IntrinsicElements {
        "add-task": AddTask;
        "my-component": MyComponent;
        "task-filter": TaskFilter;
        "task-list": TaskList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-task": LocalJSX.AddTask & JSXBase.HTMLAttributes<HTMLAddTaskElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "task-filter": LocalJSX.TaskFilter & JSXBase.HTMLAttributes<HTMLTaskFilterElement>;
            "task-list": LocalJSX.TaskList & JSXBase.HTMLAttributes<HTMLTaskListElement>;
        }
    }
}
